import { CDN_URL } from "./constants";
import type { RuleProvider } from "./types";

export const ruleProviders: Record<string, RuleProvider> = {
    ADBlock: {
        type: "http",
        behavior: "domain",
        format: "yaml",
        interval: 86400,
        url: `${CDN_URL}/gh/217heidai/adblockfilters@main/rules/adblockmihomolite.yaml`,
        path: "./ruleset/ADBlock.yaml",
    },
    StaticResources: {
        type: "http",
        behavior: "domain",
        format: "text",
        interval: 86400,
        url: "https://ruleset.skk.moe/Clash/domainset/cdn.txt",
        path: "./ruleset/StaticResources.txt",
    },
    CDNResources: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: "https://ruleset.skk.moe/Clash/non_ip/cdn.txt",
        path: "./ruleset/CDNResources.txt",
    },
    TikTok: {
        type: "http",
        behavior: "domain",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/Zer0wAve/zer0plan@main/ruleset/converted/TikTok.txt`,
        path: "./ruleset/converted/TikTok.txt",
    },
    EHentai: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/powerfullz/override-rules@master/ruleset/EHentai.list`,
        path: "./ruleset/EHentai.list",
    },
    SteamFix: {
        type: "http",
        behavior: "domain",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/Zer0wAve/zer0plan@main/ruleset/converted/SteamFix.txt`,
        path: "./ruleset/converted/SteamFix.txt",
    },
    GoogleFCM: {
        type: "http",
        behavior: "classical",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/powerfullz/override-rules@master/ruleset/FirebaseCloudMessaging.list`,
        path: "./ruleset/FirebaseCloudMessaging.list",
    },
    AdditionalFilter: {
        type: "http",
        behavior: "domain",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/Zer0wAve/zer0plan@main/ruleset/converted/AdditionalFilter.txt`,
        path: "./ruleset/converted/AdditionalFilter.txt",
    },
    AdditionalCDNResources: {
        type: "http",
        behavior: "domain",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/Zer0wAve/zer0plan@main/ruleset/converted/AdditionalCDNResources.txt`,
        path: "./ruleset/converted/AdditionalCDNResources.txt",
    },
    Crypto: {
        type: "http",
        behavior: "domain",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/Zer0wAve/zer0plan@main/ruleset/converted/Crypto.txt`,
        path: "./ruleset/converted/Crypto.txt",
    },
    GFWList: {
        type: "http",
        behavior: "domain",
        format: "yaml",
        interval: 86400,
        url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt",
        path: "./ruleset/GFWList.yaml",
    },
    zer0direct: {
        type: "http",
        behavior: "domain",
        format: "yaml",
        interval: 86400,
        url: `${CDN_URL}/gh/Zer0wAve/zer0plan@main/ruleset/zer0direct.txt`,
        path: "./ruleset/zer0direct.txt",
    },
    zer0proxy: {
        type: "http",
        behavior: "domain",
        format: "yaml",
        interval: 86400,
        url: `${CDN_URL}/gh/Zer0wAve/zer0plan@main/ruleset/zer0proxy.txt`,
        path: "./ruleset/zer0proxy.txt",
    },
    BiliIntl: {
        type: "http",
        behavior: "domain",
        format: "text",
        interval: 86400,
        url: `${CDN_URL}/gh/xishang0128/rules@main/biliintl.list`,
        path: "./ruleset/BiliIntl.list",
    },
};
